name: 📚 Documentation
description: Report documentation issues
title: "[DOCS] "
labels: ["documentation"]

body:
  - type: textarea
    id: issue-description
    attributes:
      label: What's wrong with the docs?
      placeholder: What needs to be fixed or added?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      placeholder: Page links, suggestions, etc.