name: ✨ Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: What feature do you want?
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      placeholder: Why would this be useful?
