name: ✨ Feature Request
description: Suggest a new feature for AIToolbox.software
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: ✨ What feature would you like?
      description: Describe the feature you want to see added
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 🎨 How would you use it?
      description: Tell us how this feature would be helpful
      placeholder: Explain how you would use this feature...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Anything else?
      description: Any other details or context
