name: 🚀 Improvement
description: Suggest an improvement
title: "[IMPROVEMENT] "
labels: ["improvement"]

body:
  - type: textarea
    id: improvement-description
    attributes:
      label: What should be improved?
      placeholder: Describe what you'd like to see improved...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      placeholder: Why would this improvement help?