name: ❓ Question
description: Ask a question
title: "[QUESTION] "
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      placeholder: Ask anything...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Anything else?
      placeholder: Context, what you tried, etc.