name: ❓ Question/Support
description: Ask a question or get support for AIToolbox.software
title: "[QUESTION] "
labels: ["question", "support", "needs-triage"]
assignees: []

body:
  - type: dropdown
    id: question-category
    attributes:
      label: 🏷️ What's your question about?
      description: Choose the closest category
      options:
        - General Usage
        - Setup/Installation
        - Contributing/Development
        - Troubleshooting
        - Other
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: ❓ Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🔍 Context (optional)
      description: Any relevant background information
      placeholder: |
        - What are you trying to achieve?
        - What have you already tried?

  - type: textarea
    id: additional-info
    attributes:
      label: 📝 Anything else?
      description: Any other details that might help