import type { Metadata } from "next";

export const revalidate = 86400; // ISR for a day

export const metadata: Metadata = {
  title: "Terms of Service - AI Toolbox",
  description:
    "Terms of Service for using AI Toolbox. Please read these terms carefully before using our free AI tools.",
  keywords: [
    "terms of service",
    "terms and conditions",
    "user agreement",
    "AI tools usage",
  ],
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="font-serif text-4xl mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">
        Last Updated: {new Date().toLocaleDateString()}
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">1. Acceptance of Terms</h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        By accessing and using{" "}
        <strong className="font-medium text-foreground">AI Toolbox</strong>{" "}
        (aitoolbox.software), you accept and agree to be bound by the terms and
        provision of this agreement. In addition, when using these particular
        services, you shall be subject to any posted guidelines or rules
        applicable to such services.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">
        2. Description of Service
      </h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        AI Toolbox provides users with access to a collection of resources,
        including various AI-powered tools (image generation, text editing,
        etc.). You understand and agree that the Service is provided "AS-IS" and
        that AI Toolbox assumes no responsibility for the timeliness, deletion,
        mis-delivery, or failure to store any user communications or
        personalization settings.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">3. User Conduct</h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        You agree to use the website only for lawful purposes. You are
        prohibited from using the site to generate content that is illegal,
        harmful, threatening, abusive, harassing, defamatory, vulgar, obscene,
        or otherwise objectionable.
        <strong className="font-medium text-foreground">
          {" "}
          We strictly prohibit the generation of Non-Consensual Sexual Content
          (NCSC), Child Sexual Abuse Material (CSAM), or any form of hate
          speech.
        </strong>
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">
        4. Intellectual Property
      </h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        The content generated by our AI tools is generally yours to use, subject
        to the terms of the underlying AI models (e.g., Pollination API).
        However, AI Toolbox retains rights to the design, layout, and code of
        the website itself.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">
        5. Disclaimer of Warranties
      </h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        The services are provided on an "as is" and "as available" basis. AI
        Toolbox expressly disclaims all warranties of any kind, whether express
        or implied, including, but not limited to, the implied warranties of
        merchantability, fitness for a particular purpose, and non-infringement.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">
        6. Limitation of Liability
      </h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        In no event shall AI Toolbox be liable for any direct, indirect,
        incidental, special, consequential, or exemplary damages resulting from
        the use or the inability to use the service.
      </p>

      <h2 className="font-serif text-2xl mt-8 mb-4">7. Changes to Terms</h2>
      <p className="leading-relaxed text-muted-foreground mb-6">
        We reserve the right to modify these terms at any time. You should check
        this page regularly. Your continued use of the Service after any such
        changes constitutes your acceptance of the new Terms of Service.
      </p>
    </div>
  );
}
